// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson634273f8DecodeGithubComGoParkMailRu20221VVTI20InternalAppModels(in *jlexer.Lexer, out *GetCommentsDataDelivery) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "comment":
			if in.IsNull() {
				in.Skip()
				out.Comment = nil
			} else {
				in.Delim('[')
				if out.Comment == nil {
					if !in.IsDelim(']') {
						out.Comment = make([]GetCommentDataDelivery, 0, 1)
					} else {
						out.Comment = []GetCommentDataDelivery{}
					}
				} else {
					out.Comment = (out.Comment)[:0]
				}
				for !in.IsDelim(']') {
					var v1 GetCommentDataDelivery
					(v1).UnmarshalEasyJSON(in)
					out.Comment = append(out.Comment, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson634273f8EncodeGithubComGoParkMailRu20221VVTI20InternalAppModels(out *jwriter.Writer, in GetCommentsDataDelivery) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"comment\":"
		out.RawString(prefix[1:])
		if in.Comment == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Comment {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetCommentsDataDelivery) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson634273f8EncodeGithubComGoParkMailRu20221VVTI20InternalAppModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetCommentsDataDelivery) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson634273f8EncodeGithubComGoParkMailRu20221VVTI20InternalAppModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetCommentsDataDelivery) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson634273f8DecodeGithubComGoParkMailRu20221VVTI20InternalAppModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetCommentsDataDelivery) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson634273f8DecodeGithubComGoParkMailRu20221VVTI20InternalAppModels(l, v)
}
func easyjson634273f8DecodeGithubComGoParkMailRu20221VVTI20InternalAppModels1(in *jlexer.Lexer, out *GetCommentDataDelivery) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "author":
			out.Author = string(in.String())
		case "text":
			out.Text = string(in.String())
		case "stars":
			out.Stars = int(in.Int())
		case "date":
			out.Date = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson634273f8EncodeGithubComGoParkMailRu20221VVTI20InternalAppModels1(out *jwriter.Writer, in GetCommentDataDelivery) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"author\":"
		out.RawString(prefix[1:])
		out.String(string(in.Author))
	}
	{
		const prefix string = ",\"text\":"
		out.RawString(prefix)
		out.String(string(in.Text))
	}
	{
		const prefix string = ",\"stars\":"
		out.RawString(prefix)
		out.Int(int(in.Stars))
	}
	{
		const prefix string = ",\"date\":"
		out.RawString(prefix)
		out.String(string(in.Date))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetCommentDataDelivery) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson634273f8EncodeGithubComGoParkMailRu20221VVTI20InternalAppModels1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetCommentDataDelivery) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson634273f8EncodeGithubComGoParkMailRu20221VVTI20InternalAppModels1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetCommentDataDelivery) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson634273f8DecodeGithubComGoParkMailRu20221VVTI20InternalAppModels1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetCommentDataDelivery) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson634273f8DecodeGithubComGoParkMailRu20221VVTI20InternalAppModels1(l, v)
}
func easyjson634273f8DecodeGithubComGoParkMailRu20221VVTI20InternalAppModels2(in *jlexer.Lexer, out *CommentDataDelivery) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "restaurants_id":
			out.RestaurantId = int(in.Int())
		case "author":
			out.Author = string(in.String())
		case "text":
			out.Text = string(in.String())
		case "stars":
			out.Stars = int(in.Int())
		case "date":
			out.Date = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson634273f8EncodeGithubComGoParkMailRu20221VVTI20InternalAppModels2(out *jwriter.Writer, in CommentDataDelivery) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"restaurants_id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.RestaurantId))
	}
	{
		const prefix string = ",\"author\":"
		out.RawString(prefix)
		out.String(string(in.Author))
	}
	{
		const prefix string = ",\"text\":"
		out.RawString(prefix)
		out.String(string(in.Text))
	}
	{
		const prefix string = ",\"stars\":"
		out.RawString(prefix)
		out.Int(int(in.Stars))
	}
	{
		const prefix string = ",\"date\":"
		out.RawString(prefix)
		out.String(string(in.Date))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CommentDataDelivery) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson634273f8EncodeGithubComGoParkMailRu20221VVTI20InternalAppModels2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CommentDataDelivery) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson634273f8EncodeGithubComGoParkMailRu20221VVTI20InternalAppModels2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CommentDataDelivery) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson634273f8DecodeGithubComGoParkMailRu20221VVTI20InternalAppModels2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CommentDataDelivery) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson634273f8DecodeGithubComGoParkMailRu20221VVTI20InternalAppModels2(l, v)
}
func easyjson634273f8DecodeGithubComGoParkMailRu20221VVTI20InternalAppModels3(in *jlexer.Lexer, out *AddCommentRestaurantReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "slug":
			out.Slug = string(in.String())
		case "text":
			out.CommentText = string(in.String())
		case "stars":
			out.CommentRating = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson634273f8EncodeGithubComGoParkMailRu20221VVTI20InternalAppModels3(out *jwriter.Writer, in AddCommentRestaurantReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"slug\":"
		out.RawString(prefix[1:])
		out.String(string(in.Slug))
	}
	{
		const prefix string = ",\"text\":"
		out.RawString(prefix)
		out.String(string(in.CommentText))
	}
	{
		const prefix string = ",\"stars\":"
		out.RawString(prefix)
		out.Int(int(in.CommentRating))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AddCommentRestaurantReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson634273f8EncodeGithubComGoParkMailRu20221VVTI20InternalAppModels3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AddCommentRestaurantReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson634273f8EncodeGithubComGoParkMailRu20221VVTI20InternalAppModels3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AddCommentRestaurantReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson634273f8DecodeGithubComGoParkMailRu20221VVTI20InternalAppModels3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AddCommentRestaurantReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson634273f8DecodeGithubComGoParkMailRu20221VVTI20InternalAppModels3(l, v)
}
