// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson47dfb384DecodeGithubComGoParkMailRu20221VVTI20InternalAppModels(in *jlexer.Lexer, out *GetRestaurantDishesResp) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.Id = int(in.Int())
		case "restName":
			out.Name = string(in.String())
		case "imgPath":
			out.ImagePath = string(in.String())
		case "slug":
			out.Slug = string(in.String())
		case "minPrice":
			out.MinPrice = int(in.Int())
		case "rating":
			out.Rating = float64(in.Float64())
		case "timeToDeliver":
			out.TimeToDelivery = string(in.String())
		case "reviewCount":
			out.ReviewCount = int(in.Int())
		case "dishes":
			if in.IsNull() {
				in.Skip()
				out.Dishes = nil
			} else {
				in.Delim('[')
				if out.Dishes == nil {
					if !in.IsDelim(']') {
						out.Dishes = make([]DishResp, 0, 0)
					} else {
						out.Dishes = []DishResp{}
					}
				} else {
					out.Dishes = (out.Dishes)[:0]
				}
				for !in.IsDelim(']') {
					var v1 DishResp
					(v1).UnmarshalEasyJSON(in)
					out.Dishes = append(out.Dishes, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson47dfb384EncodeGithubComGoParkMailRu20221VVTI20InternalAppModels(out *jwriter.Writer, in GetRestaurantDishesResp) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Id))
	}
	{
		const prefix string = ",\"restName\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"imgPath\":"
		out.RawString(prefix)
		out.String(string(in.ImagePath))
	}
	{
		const prefix string = ",\"slug\":"
		out.RawString(prefix)
		out.String(string(in.Slug))
	}
	{
		const prefix string = ",\"minPrice\":"
		out.RawString(prefix)
		out.Int(int(in.MinPrice))
	}
	{
		const prefix string = ",\"rating\":"
		out.RawString(prefix)
		out.Float64(float64(in.Rating))
	}
	{
		const prefix string = ",\"timeToDeliver\":"
		out.RawString(prefix)
		out.String(string(in.TimeToDelivery))
	}
	{
		const prefix string = ",\"reviewCount\":"
		out.RawString(prefix)
		out.Int(int(in.ReviewCount))
	}
	{
		const prefix string = ",\"dishes\":"
		out.RawString(prefix)
		if in.Dishes == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Dishes {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetRestaurantDishesResp) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson47dfb384EncodeGithubComGoParkMailRu20221VVTI20InternalAppModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetRestaurantDishesResp) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson47dfb384EncodeGithubComGoParkMailRu20221VVTI20InternalAppModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetRestaurantDishesResp) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson47dfb384DecodeGithubComGoParkMailRu20221VVTI20InternalAppModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetRestaurantDishesResp) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson47dfb384DecodeGithubComGoParkMailRu20221VVTI20InternalAppModels(l, v)
}
func easyjson47dfb384DecodeGithubComGoParkMailRu20221VVTI20InternalAppModels1(in *jlexer.Lexer, out *DishResp) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.Id = int(in.Int())
		case "restaurant":
			out.RestaurantId = int(in.Int())
		case "productName":
			out.Name = string(in.String())
		case "description":
			out.Description = string(in.String())
		case "imgPath":
			out.ImagePath = string(in.String())
		case "info":
			out.Calories = int(in.Int())
		case "price":
			out.Price = int(in.Int())
		case "weight":
			out.Weight = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson47dfb384EncodeGithubComGoParkMailRu20221VVTI20InternalAppModels1(out *jwriter.Writer, in DishResp) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Id))
	}
	{
		const prefix string = ",\"restaurant\":"
		out.RawString(prefix)
		out.Int(int(in.RestaurantId))
	}
	{
		const prefix string = ",\"productName\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"imgPath\":"
		out.RawString(prefix)
		out.String(string(in.ImagePath))
	}
	{
		const prefix string = ",\"info\":"
		out.RawString(prefix)
		out.Int(int(in.Calories))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Int(int(in.Price))
	}
	{
		const prefix string = ",\"weight\":"
		out.RawString(prefix)
		out.Int(int(in.Weight))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v DishResp) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson47dfb384EncodeGithubComGoParkMailRu20221VVTI20InternalAppModels1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DishResp) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson47dfb384EncodeGithubComGoParkMailRu20221VVTI20InternalAppModels1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DishResp) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson47dfb384DecodeGithubComGoParkMailRu20221VVTI20InternalAppModels1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DishResp) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson47dfb384DecodeGithubComGoParkMailRu20221VVTI20InternalAppModels1(l, v)
}
