// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson3711ab1aDecodeGithubComGoParkMailRu20221VVTI20InternalAppModels(in *jlexer.Lexer, out *RecommendationsReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "restId":
			out.RestId = int64(in.Int64())
		case "orderList":
			if in.IsNull() {
				in.Skip()
				out.OrderList = nil
			} else {
				in.Delim('[')
				if out.OrderList == nil {
					if !in.IsDelim(']') {
						out.OrderList = make([]RecommendationsOrderPosition, 0, 8)
					} else {
						out.OrderList = []RecommendationsOrderPosition{}
					}
				} else {
					out.OrderList = (out.OrderList)[:0]
				}
				for !in.IsDelim(']') {
					var v1 RecommendationsOrderPosition
					(v1).UnmarshalEasyJSON(in)
					out.OrderList = append(out.OrderList, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3711ab1aEncodeGithubComGoParkMailRu20221VVTI20InternalAppModels(out *jwriter.Writer, in RecommendationsReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"restId\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.RestId))
	}
	{
		const prefix string = ",\"orderList\":"
		out.RawString(prefix)
		if in.OrderList == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.OrderList {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RecommendationsReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3711ab1aEncodeGithubComGoParkMailRu20221VVTI20InternalAppModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RecommendationsReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3711ab1aEncodeGithubComGoParkMailRu20221VVTI20InternalAppModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RecommendationsReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3711ab1aDecodeGithubComGoParkMailRu20221VVTI20InternalAppModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RecommendationsReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3711ab1aDecodeGithubComGoParkMailRu20221VVTI20InternalAppModels(l, v)
}
func easyjson3711ab1aDecodeGithubComGoParkMailRu20221VVTI20InternalAppModels1(in *jlexer.Lexer, out *RecommendationsOrderPosition) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.Id = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3711ab1aEncodeGithubComGoParkMailRu20221VVTI20InternalAppModels1(out *jwriter.Writer, in RecommendationsOrderPosition) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Id))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RecommendationsOrderPosition) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3711ab1aEncodeGithubComGoParkMailRu20221VVTI20InternalAppModels1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RecommendationsOrderPosition) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3711ab1aEncodeGithubComGoParkMailRu20221VVTI20InternalAppModels1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RecommendationsOrderPosition) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3711ab1aDecodeGithubComGoParkMailRu20221VVTI20InternalAppModels1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RecommendationsOrderPosition) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3711ab1aDecodeGithubComGoParkMailRu20221VVTI20InternalAppModels1(l, v)
}
func easyjson3711ab1aDecodeGithubComGoParkMailRu20221VVTI20InternalAppModels2(in *jlexer.Lexer, out *RecommendationResp) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.Id = int(in.Int())
		case "category":
			out.Category = int(in.Int())
		case "restaurant":
			out.RestaurantId = int(in.Int())
		case "productName":
			out.Name = string(in.String())
		case "description":
			out.Description = string(in.String())
		case "imgPath":
			out.ImagePath = string(in.String())
		case "info":
			out.Calories = int(in.Int())
		case "price":
			out.Price = int(in.Int())
		case "weight":
			out.Weight = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3711ab1aEncodeGithubComGoParkMailRu20221VVTI20InternalAppModels2(out *jwriter.Writer, in RecommendationResp) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Id))
	}
	{
		const prefix string = ",\"category\":"
		out.RawString(prefix)
		out.Int(int(in.Category))
	}
	{
		const prefix string = ",\"restaurant\":"
		out.RawString(prefix)
		out.Int(int(in.RestaurantId))
	}
	{
		const prefix string = ",\"productName\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"imgPath\":"
		out.RawString(prefix)
		out.String(string(in.ImagePath))
	}
	{
		const prefix string = ",\"info\":"
		out.RawString(prefix)
		out.Int(int(in.Calories))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Int(int(in.Price))
	}
	{
		const prefix string = ",\"weight\":"
		out.RawString(prefix)
		out.Int(int(in.Weight))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RecommendationResp) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3711ab1aEncodeGithubComGoParkMailRu20221VVTI20InternalAppModels2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RecommendationResp) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3711ab1aEncodeGithubComGoParkMailRu20221VVTI20InternalAppModels2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RecommendationResp) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3711ab1aDecodeGithubComGoParkMailRu20221VVTI20InternalAppModels2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RecommendationResp) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3711ab1aDecodeGithubComGoParkMailRu20221VVTI20InternalAppModels2(l, v)
}
